version: '3'

services:
  postgres:
    image: postgres:14.6-bullseye
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-rabbitmq}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-rabbitmq}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
  django:
    image: harleyking/dj-ms-${DJ_MS_APP_LABEL:-core}:${DJ_MS_CORE_VERSION:-latest}
    build:
      context: .
    healthcheck:
      test: curl -f http://localhost:8000/health || exit 1
      interval: 3s
      timeout: 3s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
          condition: service_healthy
    environment:
      - BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER:-rabbitmq}:${RABBITMQ_DEFAULT_PASS:-rabbitmq}@rabbitmq:5672
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres/${POSTGRES_DB:-postgres}
    env_file:
      - .env
  celery:
    image: harleyking/dj-ms-${DJ_MS_APP_LABEL:-core}:${DJ_MS_CORE_VERSION:-latest}
    build:
      context: .
    command: celery -A core worker -l info --concurrency 1 -P solo -E
    depends_on:
      django:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
          condition: service_healthy
    environment:
      - BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER:-rabbitmq}:${RABBITMQ_DEFAULT_PASS:-rabbitmq}@rabbitmq:5672
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres/${POSTGRES_DB:-postgres}
    env_file:
      - .env
  celery-beat:
    image: harleyking/dj-ms-${DJ_MS_APP_LABEL:-core}:${DJ_MS_CORE_VERSION:-latest}
    build:
      context: .
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler
    depends_on:
      django:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
          condition: service_healthy
    environment:
      - BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER:-rabbitmq}:${RABBITMQ_DEFAULT_PASS:-rabbitmq}@rabbitmq:5672
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres/${POSTGRES_DB:-postgres}
    env_file:
      - .env


volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_log:
