services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  django:
    ports:
      - "${DJANGO_WEB_PORT:-8000}:8000"
    volumes:
      - .:/home/django/
  celery:
    volumes:
      - .:/home/django/
  celery-beat:
    volumes:
      - .:/home/django/
  telegram-bot:
    image: harleyking/dj-ms-${DJ_MS_APP_LABEL:-core}:${DJ_MS_CORE_VERSION:-latest}
    build:
      context: .
    command: python run_polling.py
    depends_on:
      django:
          condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
          condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}
      - BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER:-rabbitmq}:${RABBITMQ_DEFAULT_PASS:-rabbitmq}@rabbitmq:5672
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres/${POSTGRES_DB:-postgres}
    env_file:
      - .env

volumes:
  pgadmin_data:
